name: cvut_study_manager
description: A new Flutter project.
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  url_launcher: ^6.1.14
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
